### ISSUE TITLE
cpu run

### ISSUE THREAD

**Issue by justinner** [DrSleep/light-weight-refinenet#1]
Hi,
 It is my pleasure to learn your code ,but i do not have a capable GPU,so could you tell me how i run the codes in CPU? I have run .but runtime error occured, does CPU need cuda?

**Comment by DrSleep** [comment]
Hi, could you please post the error? I have added the `has_cuda` flag inside the notebooks, which should guide the code to be run using CPU

**Comment by justinner** [comment]
You are welcome ,I will run it again,I am very glad to learn from you .
