### ISSUE TITLE
Can you share your cityscapes results and fps?

### ISSUE THREAD

**Issue by chenxiaoyu523** [DrSleep/light-weight-refinenet#10]
hey! i am doing some experiments on  semantic segmentation in street scenes. i found that you put the cityscapes result in your paper  supplementary materials. can you share your cityscapes results and fps?

**Comment by DrSleep** [comment]
I have only trained ResNet-101 - it achieved 72.1% mIoU on the test set.
Regarding FPS, I do not currently have the same setup on my desktop, here are the numbers I am getting with 1080Ti:

> Size: torch.Size([1024, 1024]), : AVG: 78.1693 / 12.7928 ms/fps, STD: 0.8807ms
> Size: torch.Size([1024, 2048]), : AVG: 150.2748 / 6.6545 ms/fps, STD: 3.0682ms

**Comment by moonmyth** [comment]
how can i train with cityscapes with your train code?
