### ISSUE TITLE
Mnasnet

### ISSUE THREAD

**Issue by bhack** [DrSleep/light-weight-refinenet#12]
What about MNasnet https://github.com/AnjieZheng/MNasnet-Pytorch?

**Comment by DrSleep** [comment]
What is about it?

**Comment by bhack** [comment]
Cause I've seen that you was experimenting with Mobilenetv2. MNasnet seems to improve over that.

**Comment by bhack** [comment]
https://arxiv.org/abs/1807.11626

**Comment by DrSleep** [comment]
Yeah, that paper was uploaded much later. And I think no one fully reproduced it

**Comment by bhack** [comment]
As it is a "Google" paper let see if they will release a reference impl. https://github.com/tensorflow/models/issues/5761

**Comment by DrSleep** [comment]
sounds good
