### ISSUE TITLE
Is this repo under MIT?

### ISSUE THREAD

**Issue by bhack** [DrSleep/light-weight-refinenet#14]
The Readme tells MIT but the content of the link not https://github.com/DrSleep/light-weight-refinenet#license

**Comment by DrSleep** [comment]
2-clause BSD, updated README

**Comment by bhack** [comment]
Thanks for the clarification. Could you align also some source file header that has the old text?

**Comment by bhack** [comment]
The License is not BSD https://github.com/DrSleep/light-weight-refinenet/blob/master/LICENSE

**Comment by DrSleep** [comment]
the license text stays the same

https://opensource.org/licenses/BSD-2-Clause

**Comment by bhack** [comment]
I read "for non-commercial purposes" in License and source files that is not BSD

**Comment by bhack** [comment]
https://github.com/DrSleep/light-weight-refinenet/search?q=for+non-commercial+purposes&unscoped_q=for+non-commercial+purposes

**Comment by DrSleep** [comment]
Modified BSD then.
This is not going to be changed.

**Comment by DrSleep** [comment]
yes, you are right - my wording was not exact, sorry about that
This custom license is the same as for RefineNet - https://github.com/guosheng/refinenet#license
I will make it clear in README, thanks for pointing it out in the first place

**Comment by bhack** [comment]
OK thank you for the clarification of the source. I will start from an implementation under MIT https://github.com/thomasjpfan/pytorch_refinenet
