### ISSUE TITLE
python setup.py build_ext --build-lib=./src/的时候遇到错误

### ISSUE THREAD

**Issue by 154461013** [DrSleep/light-weight-refinenet#17]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda3.5\lib\site-packages\numpy\core\include -ID:\Anaconda3.5\include -ID:\Anaconda3.5\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include" /TcF:\light-weight-refinenet-master/src/miou_utils.c /Fobuild\temp.win-amd64-3.6\Release\light-weight-refinenet-master/src/miou_utils.obj
miou_utils.c
d:\anaconda3.5\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by DrSleep** [comment]
> For flawless reproduction of our results, the Ubuntu OS is recommended

I cannot help with windows. Seems like a Cython-related issue.

[First link in Google](https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory)
