### ISSUE TITLE
How to convert the NYU depth images into the same image_size of your dataset?

### ISSUE THREAD

**Issue by zhangxgu** [DrSleep/light-weight-refinenet#19]
I download the NYU dataset from your link. As I see, the image_size are not 640*480 since you have removed the district label==255. How can I do the same thing to the depth images? Or could you give me the corresponding depth images with the same size of your RGB and segmentation mask files?

**Comment by zhangxgu** [comment]
@DrSleep

**Comment by DrSleep** [comment]
you can download rgb-masks-depth images here: https://cloudstor.aarnet.edu.au/plus/s/pQY2sgg4fffGUYy

**Comment by dyz-zju** [comment]
Hello, could you share a new link of rgb-masks-depth images? @DrSleep
