### ISSUE TITLE
Reproducing PASCAL VOC

### ISSUE THREAD

**Issue by MSiam** [DrSleep/light-weight-refinenet#23]
Hi I want to reproduce the results you have on PASCAL VOC by training on PASCAL. If you can guide me on the setup you used. So basically what was your config.py? I am assuming the config.py you're providing now is the one for NYUv2 training. Also if you can add the loader for PASCAL VOC.

Thanks

**Comment by DrSleep** [comment]
You can adapt the current code. Please read Readme carefully.
Pascal VOC hyperparameters are described in the paper

**Comment by xiaoyuamw** [comment]
> Hi I want to reproduce the results you have on PASCAL VOC by training on PASCAL. If you can guide me on the setup you used. So basically what was your config.py? I am assuming the config.py you're providing now is the one for NYUv2 training. Also if you can add the loader for PASCAL VOC.
> 
> Thanks

Hi @MSiam 

Can you tell me whether you had trained the model on PASCAL VOC successfully? If you did, can you tell me how to treat with the datasets and what codes should changed?

Thank you very much!

Best Regards.
