### ISSUE TITLE
PASCAL Person-Part dataset

### ISSUE THREAD

**Issue by FengZhiTeng** [DrSleep/light-weight-refinenet#24]
I want to retrain on the PASCAL Person-Part dataset, could you please send me the Person-Part dataset, thank you

**Comment by DrSleep** [comment]
it is available online.

**Comment by xiakj** [comment]
@DrSleep can you provide me the download link of PASCAL Person-Part dataset?

**Comment by DrSleep** [comment]
http://liangchiehchen.com/data/pascal_person_part.zip
