### ISSUE TITLE
Is the label a binary image or an RGB image?

### ISSUE THREAD

**Issue by lucy3589** [DrSleep/light-weight-refinenet#26]
Is the label a binary image or an RGB image? I used the non-binary image to report errors all the time. There are two classes : objects and backgrounds

**Comment by zswmr** [comment]
gray image i thought

**Comment by lucy3589** [comment]
> gray image i thought
but opendataset is colorful

**Comment by zswmr** [comment]
> > gray image i thought
> > but opendataset is colorful

you can transform it, in nyuv2 , its labled img is gray

**Comment by lucy3589** [comment]
> > > gray image i thought
> > > but opendataset is colorful
> 
> you can transform it, in nyuv2 , its labled img is gray

If I want to make my own data sets, how do I process my labels?

**Comment by zswmr** [comment]
> > > > gray image i thought
> > > > but opendataset is colorful
> > 
> > 
> > you can transform it, in nyuv2 , its labled img is gray
> 
> If I want to make my own data sets, how do I process my labels?

make  mask imgs, for example, 0 is class one, 1 is class two, and background is 255

**Comment by lucy3589** [comment]
> > > gray image i thought
> > > but opendataset is colorful
> 
> you can transform it, in nyuv2 , its labled img is gray

**Comment by lucy3589** [comment]
> > > > > gray image i thought
> > > > > but opendataset is colorful
> > > 
> > > 
> > > you can transform it, in nyuv2 , its labled img is gray
> > 
> > 
> > If I want to make my own data sets, how do I process my labels?
> 
> make mask imgs, for example, 0 is class one, 1 is class two, and background is 255

I am also training this model now. Can we further communicate?My WeChat is:zlblzl
