### ISSUE TITLE
I train NYU,but the results of your model  is better than the ones I train with your own program.

### ISSUE THREAD

**Issue by lucy3589** [DrSleep/light-weight-refinenet#28]
when I train your model,mean iou<0.5

**Comment by st2yang** [comment]
@lucy3589 
I think the mean IoU for NYUD should be around 42%, since the best IoU reported on the paper is 44.4%. 
The very high IoU (over 82%) is for Pascal VOC. But NYUD should be much more complex than Pascal VOC.

**Comment by DrSleep** [comment]
well, we also did not get >= 0.5, so it is fine
