### ISSUE TITLE
How to train on Custom Dataset?

### ISSUE THREAD

**Issue by noumanriazkhan** [DrSleep/light-weight-refinenet#3]
Bravo for nice work!

I am also interested in retraining for Person Parts for custom dataset, any roadmap to do so?

Thanks

**Comment by DrSleep** [comment]
No roadmap so far, unfortunately. Once time permits, there will be an example.

For now, you can refer to the paper for the set of hyperparameters and re-use existing pytorch segmentation pipelines.
