### ISSUE TITLE
what about the highest IoU can arrive in PASCAL VOC in this repositority？

### ISSUE THREAD

**Issue by zhouyuan888888** [DrSleep/light-weight-refinenet#31]
hello, very nice to meet this repositority.I think there are a little difference from paper in your code.I also writer a  script to reproduce the paper but I can't make the val mIoU=80.3 test mIoU=82.0 , which are  reported by author.so what's the best performance in this repositority.
 thankyou for your answer.

**Comment by DrSleep** [comment]
we provide the pre-trained models with the results mentioned in the paper alongside training scripts for ResNet-models on NYUDv2 (achieves same or even better results). Please refer to README.
