### ISSUE TITLE
Beginning with epoch 1,loss is equal to 0

### ISSUE THREAD

**Issue by goldcarpenter** [DrSleep/light-weight-refinenet#32]
Your examples/notebook's work is wonderful.thank you.
Now, I hope to use our dataset. It ran well ,but loss was too small.Like this,
`Train epoch: 0 [0/512]	Avg. Loss: 0.701	Avg. Time: 1.706
INFO:__main__: Train epoch: 0 [10/512]	Avg. Loss: 0.589	Avg. Time: 0.434
INFO:__main__: Train epoch: 0 [20/512]	Avg. Loss: 0.407	Avg. Time: 0.374
`
Finally,we got nothing except red in predict result.
our dataset is medical image, gt is white(255).we set NUM_CLASSES = 2.Is that right?

**Comment by DrSleep** [comment]
closing since this is not related to the code released here.

**Comment by kingyj7** [comment]
Hi, @goldcarpenter , I also encounter this problem! When I  set NUM_CLASSES = 2 for my own data to classify foreground and background, the loss down to 0 quickly. And after 5 epochs, i got mIOU=1 for all validation images! If you have solved this problem, please let me know, Thank you~
