### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DataParallel

### ISSUE THREAD

**Issue by LiKunWHU** [DrSleep/light-weight-refinenet#37]
I am so sorry that I am a freshman for it, I just change  NUM_CLASSES = [40] * 3 in this file(config.py) to NUM_CLASSES = [2] * 3 because of my train(val) datasets needed to be devided into 2 classes.

but it run,and error:

INFO:__main__: Loaded Segmenter 50, ImageNet-Pre-Trained=True, #PARAMS=27.31M
Traceback (most recent call last):
  File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 432, in <module>
    main()
  File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 367, in main
    best_val, epoch_start = load_ckpt(args.ckpt_path, {'segmenter' : segmenter})
  File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 240, in load_ckpt
    v.load_state_dict(ckpt[k])
  File "D:\Soft\Anaconda_\envs\dp\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.clf_conv.weight: copying a param with shape torch.Size([40, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([2, 256, 3, 3]).
	size mismatch for module.clf_conv.bias: copying a param with shape torch.Size([40]) from checkpoint, the shape in current model is torch.Size([2]).

Could someone help me ?    please~~~

**Comment by DrSleep** [comment]
looks like you are trying to load from "args.ckpt_path", which defines the model with 40 classes, while you created the model with 2. You either need to provide correct ckpt_path to the model with 2 classes (if it exists), or omit that path altogether

**Comment by haifeng11** [comment]
> I am so sorry that I am a freshman for it, I just change NUM_CLASSES = [40] * 3 in this file(config.py) to NUM_CLASSES = [2] * 3 because of my train(val) datasets needed to be devided into 2 classes.
> 
> but it run,and error:
> 
> INFO:**main**: Loaded Segmenter 50, ImageNet-Pre-Trained=True, #PARAMS=27.31M
> Traceback (most recent call last):
> File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 432, in
> main()
> File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 367, in main
> best_val, epoch_start = load_ckpt(args.ckpt_path, {'segmenter' : segmenter})
> File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 240, in load_ckpt
> v.load_state_dict(ckpt[k])
> File "D:\Soft\Anaconda_\envs\dp\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for DataParallel:
> size mismatch for module.clf_conv.weight: copying a param with shape torch.Size([40, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([2, 256, 3, 3]).
> size mismatch for module.clf_conv.bias: copying a param with shape torch.Size([40]) from checkpoint, the shape in current model is torch.Size([2]).
> 
> Could someone help me ? please~~~

Hi@LiKunWHU
I also met such an error now and don't know how to solve it! So, i want to ask whether you had solved it before? if so, can you tell me how you do?

Thank you very much!

Best Regards.

**Comment by xiaoyuamw** [comment]
> I am so sorry that I am a freshman for it, I just change NUM_CLASSES = [40] * 3 in this file(config.py) to NUM_CLASSES = [2] * 3 because of my train(val) datasets needed to be devided into 2 classes.
> 
> but it run,and error:
> 
> INFO:**main**: Loaded Segmenter 50, ImageNet-Pre-Trained=True, #PARAMS=27.31M
> Traceback (most recent call last):
> File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 432, in
> main()
> File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 367, in main
> best_val, epoch_start = load_ckpt(args.ckpt_path, {'segmenter' : segmenter})
> File "C:/Users/likun3/Documents/light-weight-refinenet-master/src/train.py", line 240, in load_ckpt
> v.load_state_dict(ckpt[k])
> File "D:\Soft\Anaconda_\envs\dp\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for DataParallel:
> size mismatch for module.clf_conv.weight: copying a param with shape torch.Size([40, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([2, 256, 3, 3]).
> size mismatch for module.clf_conv.bias: copying a param with shape torch.Size([40]) from checkpoint, the shape in current model is torch.Size([2]).
> 
> Could someone help me ? please~~~

Hi @LiKunWHU 

I also met such an error now and don't know how to solve it! So, i want to ask whether you had solved it before? if so, can you tell me how you do?

Thank you very much!

Best Regards.
