### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by QianshengGu** [DrSleep/light-weight-refinenet#39]
Hi, @DrSleep , I am appreciate for your works, but when I directly run the scripts named train/nyu.sh, it run on three NVIDIA 1080ti cards but got blocked when evaluating the trained model after 16 epoches, I tried to change the value of num_workers in src/config.py from 16 to 1, it still occurred. But, when I set it to zero, it works, the training procedure would not be blocked, can you enplane it? Thanks a lot.

**Comment by DrSleep** [comment]
can you try to add this line "cv2.setNumThreads(0)" [here](https://github.com/DrSleep/light-weight-refinenet/blob/master/src/datasets.py#L40) ?
there was an issue before with PyTorch and cv2 multi-processing, might be that

**Comment by DrSleep** [comment]
closing it for now. feel free to comment in case you still experience the problem
