### ISSUE TITLE
Confusion about task_idx

### ISSUE THREAD

**Issue by MihaiDogariu** [DrSleep/light-weight-refinenet#42]
Hi! Great work with this repo!

I have a question regarding how you structured the training process. Why do you have 3-dimensional values in the config file? 

I've seen that the `task_idx` value will iterate until it reaches the value of `num_stages` (which is assigned the depth of the `num_classes` variable, i.e. 3) and I am not sure of what it means or why it is used.

Thanks!

**Comment by DrSleep** [comment]
Essentially, we divide our training into 3 stages as written here: https://github.com/DrSleep/light-weight-refinenet#training-scripts

The idea is to reduce the learning rate at the end of each stage; optionally, you can choose not only the learning rate but also other variables for each stage, hence why almost all parameters are of length 3
