### ISSUE TITLE
How to process NYUv2 dataset

### ISSUE THREAD

**Issue by hhhwww123** [DrSleep/light-weight-refinenet#55]
Hi，thanks to your great work.
Can you tell me how to process NYUv2 dataset (rgb&label) to the size that you provided in this project.
I want to process the NYUv2 dateset Depth data into the same size.

Thanks!

**Comment by DrSleep** [comment]
I used an already processed dataset from the original RefineNet. Maybe you could simply download the segm+depth set from here -- https://github.com/DrSleep/DenseTorch/issues/4 ?
