### ISSUE TITLE
Having a hard time reproducing the results for NYU dataset

### ISSUE THREAD

**Issue by RafayAK** [DrSleep/light-weight-refinenet#56]
Hi Vladimir, I'm having a hard time reproducing your results from training on data myself.

For example, your trained model `rf_lw50_nyu.pth.tar` provides nice results:
![Screenshot from 2020-01-22 17-12-27](https://user-images.githubusercontent.com/17025191/72893297-7fd0a880-3d3a-11ea-8c19-af50565aa6a5.png)

whereas, after training on the NYU dataset, you linked to, and using the generated `checkpoint.pth.tar` I get very weird results almost just noise.
![Screenshot from 2020-01-22 17-12-59](https://user-images.githubusercontent.com/17025191/72893375-b0b0dd80-3d3a-11ea-8e6f-07cab2ba3a1c.png)

Do you have any idea why this might be happening? Been stuck at this for a while, I'd really appreciate if you can point me in the right direction. Thanks

**Comment by DrSleep** [comment]
Maybe take a look at this one -- https://github.com/DrSleep/light-weight-refinenet/issues/34
Seems quite related

**Comment by RafayAK** [comment]
@DrSleep  Thanks a bunch👍. That was exactly the issue. I have now successfully trained a hand segmenting model thanks to your work. 
How would you propose I share my trained model? Separately, in a fork of your repo with my model? or are your welcoming to pull requests?

**Comment by DrSleep** [comment]
Glad to help :)
I don't really have a time to review PRs right now, so you may just want to create / fork a different repo and cite / link this project if you'd like. It is up to you

**Comment by xiaoyuamw** [comment]
Hi@RafayAK

Can you tell me what you had changed to solve you issue?
Thank you very much.

Best Regards.
