### ISSUE TITLE
How to infer with my own trained model?

### ISSUE THREAD

**Issue by hyclover** [DrSleep/light-weight-refinenet#62]
I appreciate your great work. I have trained this network and get checkpoint.pth.tar. Now I want to infer some examples with my model. I refered to your code in examples/notebooks/NYU.ipynb, but I am confused about what code I should change to load my model. Could you please help me? Thanks very much!

**Comment by DrSleep** [comment]
You first need to define the model you trained (i.e. MBv2, or RF-LW-50/101/152) with the appropriate number of classes.
In the notebook I show how to do it for each network, using this: `net = fun(n_classes, pretrained=True).eval().cuda()`.

You should replace `fun` with the appropriate network function and set `pretrained=False`
Then you need to load the checkpoint file, e.g. via `ckpt = torch.load(checkpoint)`
If you trained your model with GPU, then you will need to do `net = nn.DataParallel(net)` before restoring the state dict `net.load_state_dict(ckpt["model"])` (if you were not training with GPU, you can just skip the first step)

You can also see how I am loading the checkpoint here: https://github.com/DrSleep/light-weight-refinenet/blob/b6871c2d5ff84b5a22b4461deb2827a69a02a072/src_v2/train.py#L40

**Comment by hyclover** [comment]
Thanks for your reply! I have achieved it successfully according to your guidance.

**Comment by DrSleep** [comment]
Marking it as resolved

**Comment by xiaoyuamw** [comment]
Hi@hyclover

Can you tell me what you had changed to solve you issue?
Thank you very much.

Best Regards.

**Comment by xiaoyuamw** [comment]
Hi@hyclover

Can you tell me what you had changed to solve you issue?
Thank you very much.

Best Regards.
