### ISSUE TITLE
InvertedResidualBlock adding extra ConvBNReLU than the vanilla implementation 

### ISSUE THREAD

**Issue by sidhantls** [DrSleep/light-weight-refinenet#66]
According to the vanilla implementation of MobileNetV2 by PyTorch, when `expand_ratio == 1` one less `convbnrelu`is added in `InvertedResidualBlock`- as shown [here ](https://github.com/pytorch/vision/blob/aa753263b8e7b3180225e3ad1e6e5434a5f42882/torchvision/models/mobilenet.py#L75)

mobilenet.py here mentions that the InvertedResidualBlock module is the same as in the MobileNetV2, but there is a mismatch here- there is no such `expand_ratio` condition in `InvertedResidualBlock` for adding an extra `convbnrelu`. Any reason why?

**Comment by DrSleep** [comment]
i started working on light-weight-refinenet before the publication of MBv2. when the MBv2 paper was released, I incorporated it into light-weight-refinenet and resorted to use this implementation (since there were no official MBv2 implementations yet).
