### ISSUE TITLE
How to calculate the 'FLOPS' of the given model?

### ISSUE THREAD

**Issue by QianshengGu** [DrSleep/light-weight-refinenet#7]
Hi, in this paper, you compare the 'FLOPs' of different models, but I am confused about that how to get the value of one models' FLOPs', is to use some scripts or what? Thank you very much.

**Comment by DrSleep** [comment]
Hi, for other models, I am using the numbers reported by their papers.
For our models, I have adapted this code:
https://github.com/ShichenLiu/CondenseNet/blob/master/utils.py
