### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by hotfinda** [DrSleep/light-weight-refinenet#77]
Hi, Thanks for this contribution.
I am training the network with GTX 1080Ti, but it shows broken pipe. Except the batch size, which parameter can I change to reduce the cost of GPU? I only find the batch-size as (6,6,6)in the config.py, and I have change it to (1,1,1), but it still shows the problem

**Comment by DrSleep** [comment]
>but it shows broken pipe

what do you mean by this?

**Comment by hotfinda** [comment]
Hi I have solved this problem. And another question is that why you have 3 stages during training?

**Comment by DrSleep** [comment]
The first stage is COCO+BSD+VOC, the second stage is BSD+VOC, the final stage is VOC. The idea is that the VOC data contains the best quality annotations out of all three, so you can think of the first two stages as a pre-training. That is how it was done in the original RefineNet work, and I just followed it.

**Comment by hotfinda** [comment]
so if i cite this, I should cite the original paper and your code ,right?

**Comment by DrSleep** [comment]
yes, I think so
