### ISSUE TITLE
Links to pre-trained models are dead

### ISSUE THREAD

**Issue by rafay-ceoai** [DrSleep/light-weight-refinenet#80]
Hi, I don't know the state of the repo anymore, but the links to the pre-trained models are dead. Can anything be done about them?

**Comment by DrSleep** [comment]
Hi, yes, unfortunately, cloudstor was decommissioned: https://support.aarnet.edu.au/hc/en-us/articles/5697089309711-Decommissioning-CloudStor and I did not know about this until now. 

I will need to take a look to see if I have any local copies of the weights stored somewhere else (unlikely but possible).

Either way, the repo is no longer maintained, there are plenty of much better open-source semantic segmentation models around.

**Comment by RafayAK** [comment]
> Hi, yes, unfortunately, cloudstor was decommissioned: https://support.aarnet.edu.au/hc/en-us/articles/5697089309711-Decommissioning-CloudStor and I did not know about this until now.
> 
> I will need to take a look to see if I have any local copies of the weights stored somewhere else (unlikely but possible).
> 
> Either way, the repo is no longer maintained, there are plenty of much better open-source semantic segmentation models around.

Thanks for replying and hopefully looking into it (I was looking for the Pascal Human-parts pre-trained model, btw). I was trying to recreate a baseline I created a while ago through your repo. 🍻

**Comment by DrSleep** [comment]
Sorry, I could not find the weights anywhere on my local devices :( 

If you used this repo and downloaded the weights on some other device before, the weights should be saved in `~/.torch/`

**Comment by RafayAK** [comment]
Thanks for looking into it. I think I have all the data to recreate it (pretrained ImageNet -> train on Pascal  Human Parts -> Train on my own dataset.). I'll see how that goes :D
