### ISSUE TITLE
Joint semantic segmentation and depth estimation

### ISSUE THREAD

**Issue by mihaibujanca** [DrSleep/light-weight-refinenet#9]
Hi and thanks for the interesting work!
I was wondering when do you expect to release the model for joint segmentation and depth estimation?

Thanks!

**Comment by DrSleep** [comment]
hello, hopefully after the CVPR deadline it should be up

**Comment by mihaibujanca** [comment]
Any update on this by any chance?

**Comment by DrSleep** [comment]
Models are now available here: https://github.com/DrSleep/multi-task-refinenet

**Comment by mihaibujanca** [comment]
Thank you!
